config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :contents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"'
  root "dashboards#index"
end

app/models/content.rb
class Content < ApplicationRecord

    validates :title, presence: true
    validates :description, presence: true
    validates :start_date, presence: true
    validates :end_date, presence: true
  
    enum special_type: {'video': 0, 'streaming': 1, 'image': 2}
  end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: %i[ show edit update destroy ]

  def index
    @contents = Content.all
  end

  def show; end

  def new
    @content = Content.new
  end

  def edit; end

  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to content_url(@content), notice: "Content was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to content_url(@content), notice: "Content was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @content.destroy

    respond_to do |format|
      format.html { redirect_to contents_url, notice: "Content was successfully destroyed." }
    end
  end

  private
    def set_content
      @content = Content.find(params[:id])
    end

    def content_params
      params.require(:content).permit(:title, :description, :start_date, :end_date, :special_type)
    end
end

app/helpers/contents_helper.rb
module ContentsHelper

    def special_types
        Content.special_types.keys.map do |type|
            [t("activerecord.attributes.content.types.#{type}"), type]
        end
    end
end

app/helpers/contents_helpers.rb
module ContentsHelper

    def special_types
        Content.special_types.keys.map do |type|
            [t("activerecord.attributes.content.types.#{type}"), type]
        end
    end
end 

app/views/contents/_content.html.haml
%div{:id => "#{dom_id content}"}
  %p
    %strong Title:
    = content.title
  %p
    %strong Description:
    = content.description
  %p
    %strong Start date:
    = content.start_date
  %p
    %strong End date:
    = content.end_date

app/views/contents/_form.html.haml
= form_for @content, validate: true do |f|
  -if @content.errors.any?
    .card.mx-4
      .card-body
        %div{style: 'color: red'}
          %h2
            = t('application.can_not_be_saved')
          %ul
            -  @content.errors.each do |error|
              %li= error.full_message

  .form-group.mx-4
    = f.label :title, class: "form-label required"
    .div.w-25
      = f.text_field :title, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :description, class: "form-label required"
    .div.w-25
      = f.text_area :description, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :start_date, class: "form-label required"
    .div.w-25
      = f.datetime_field :start_date, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :end_date, class: "form-label required"
    .div.w-25
      = f.datetime_field :end_date, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :special_type, class: "form-label required"
    .div.w-25
      = f.select(:special_type, options_for_select(special_types, @content.special_type), {prompt: t('application.select')}, class: "form-control")

  .row.mt-4
    .offset-3.col-3
      = link_to t('application.back'), contents_path, class: "btn btn-secondary btn-block"
    .col-3
      = button_tag t('application.save'), class: "btn btn-outline-success btn-block"

app/views/contents/edit.html.haml
%h1= t('application.editing_model', model: t('activerecord.modules.content.one'))

= render "form", content: @content

app/views/contents/index.html.haml
%p{:style => "color: green"}= notice
.div.m-4
  .page.header
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.content.other'))
    .float-end.pb-4
      = link_to t('application.create'), new_content_path, class: "btn btn-primary"

  %table.table.table-striped
    %thread
      %tr
        %th= t('activerecord.attributes.content.title')
        %th= t('activerecord.attributes.content.description')
        %th= t('activerecord.attributes.content.start_date')
        %th= t('activerecord.attributes.content.end_date')
        %th
        %th
        %th
    %tbody
      -@contents.each do |content|
        %tr
          %td= content.title
          %td= content.description
          %td= content.start_date.strftime("%d/%m/%Y %I:%M %P")
          %td= content.end_date.strftime("%d/%m/%Y %I:%M %P")
          %td= link_to t('application.show'), content, class: "btn btn-info"
          %th= link_to t('application.edit'), edit_content_path(content), class: "btn btn-success"
          %th= button_to t('application.delete'), content, method: :delete, class: "btn btn-danger"

app/views/contents/new.html.haml
%h1= t('application.new_model', model: t('activerecord.modules.content.one'))
= render 'form'

app/views/contents/show.html.haml
%h1= t('activerecord.modules.content.one')

%p{:style => "color: green"}= notice
%p
  %strong= t('activerecord.attributes.content.title')
  = ':'
  = @content.title
%p
  %strong= t('activerecord.attributes.content.description')
  = ':'
  = @content.description
%p
  %strong= t('activerecord.attributes.content.start_date')
  = ':'
  = @content.start_date.strftime("%d/%m/%Y %I:%M %P")
%p
  %strong= t('activerecord.attributes.content.end_date')
  = ':'
  = @content.end_date.strftime("%d/%m/%Y %I:%M %P")

%div
  = link_to "Edit this content", edit_content_path(@content)
  |
  #{link_to "Back to contents", contents_path}

  #{link_to "Destroy this content", @content, method: :delete}