config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :contents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"'
  root "dashboards#index"
end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointments
    has_many :doctors, through: :appointments

    validates :first_name, presence: true, length: { maximum: 8 }
    validates :last_name, presence: true, length: { minimum: 3 }

end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def edit
  end

  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end
    
    def patient_params
      params.require(:patient).permit(:first_name, :last_name)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.haml
= form_for @patient do |f|
  - if @patient.errors.any?
    .card.mx-4
      .card-body
        %div{style: 'color: red'}
          %h2
            = t('application.can_not_be_saved')
          %ul
            -  @patient.errors.each do |error|
              %li= error.full_message 

  .form-group.mx-4
    = f.label :first_name, class: "form-label required"
    .dev.w-25
      = f.text_field :first_name, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :last_name, class: "form-label required"
    .dev.w-25
      = f.text_area :last_name, autofocus: true, class: "form-control"
 
  .row.mt-4
    .offset-3.col-3
      = link_to t('application.back'), patients_path, class: "btn btn-secondary btn-block"
    .col-3
      = button_tag t('application.save'), class: "btn btn-outline-success btn-block"

app/views/patients/_patient.html.haml
%div{:id => "#{dom_id patient}"}
  %p
    %strong First_name:
    = patient.first_name
  %p
    %strong Last_name:
    = patient.last_name

app/views/patients/edit.html.haml
%h1 Editing patient

= render 'form'

= link_to 'Show', @patient
\|
= link_to 'Back', patients_path

app/views/patients/index.html.haml
%p{:style => "color: green"}= notice
.div.m-4
  .page.header
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.patient.other'))
    .float-end.pb-4
      = link_to t('application.create'), new_patient_path, class: "btn btn-primary"

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.patient.first_name')
      %th= t('activerecord.attributes.patient.last_name')
      %th
      %th
      %th

  %tbody
    - @patients.each do |patient|
      %tr
        %td= patient.first_name
        %td= patient.last_name
        %td= link_to 'Show', patient, class: "btn btn-info"
        %td= link_to 'Edit', edit_patient_path(patient), class: "btn btn-success"
        %td= button_to t('application.delete'), patient, method: :delete, class: "btn btn-danger"
%br

app/views/patients/new.html.haml
%h1= t('activerecord.modules.patient.new')

= render 'form'

app/views/patients/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @patient.first_name
%p
  %b Last name:
  = @patient.last_name

= link_to 'Edit', edit_patient_path(@patient)
\|
= link_to 'Back', patients_path