config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :contents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"'
  root "dashboards#index"
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointments
    has_many :patients, through: :appointments

    validates :first_name, presence: true, length: { maximum: 8 }
    validates :last_name, presence: true, length: { minimum: 3 }
    validates :code, presence: true, uniqueness: true

end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: %i[ show edit update destroy ]

  def index
    @doctors = Doctor.all
  end

  def show
  end

  def new
    @doctor = Doctor.new
  end

  def edit
  end

  def create
    @doctor = Doctor.new(doctor_params)

    respond_to do |format|
      if @doctor.save
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully created." }
        format.json { render :show, status: :created, location: @doctor }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @doctor.update(doctor_params)
        format.html { redirect_to doctor_url(@doctor), notice: "Doctor was successfully updated." }
        format.json { render :show, status: :ok, location: @doctor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @doctor.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @doctor.destroy

    respond_to do |format|
      format.html { redirect_to doctors_url, notice: "Doctor was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:first_name, :last_name, :code)
    end
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/views/doctors/_doctor.html.haml
%div{:id => "#{dom_id doctor}"}
  %p
    %strong First_name:
    = doctor.first_name
  %p
    %strong Last_name:
    = doctor.last_name
  %p
    %strong Code:
    = doctor.code

app/views/doctors/_form.html.haml
= form_for @doctor do |f|
  - if @doctor.errors.any?
    .card.mx-4
      .card-body
        %div{style: 'color: red'}
          %h2
            = t('application.can_not_be_saved')
          %ul
            -  @doctor.errors.each do |error|
              %li= error.full_message

  .form-group.mx-4
    = f.label :first_name, class: "form-label required"
    .dev.w-25
      = f.text_field :first_name, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :last_name, class: "form-label required"
    .dev.w-25
      = f.text_area :last_name, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :code, class: "form-label required"
    .dev.w-25
      = f.text_field :code, autofocus: true, class: "form-control"
    
  .row.mt-4
    .offset-3.col-3
      = link_to t('application.back'), doctors_path, class: "btn btn-secondary btn-block"
    .col-3
      = button_tag t('application.save'), class: "btn btn-outline-success btn-block"

app/views/doctors/edit.html.haml
%h1 Editing doctor

= render 'form'

= link_to 'Show', @doctor
\|
= link_to 'Back', doctors_path

app/views/doctors/index.html.haml
%p{:style => "color: green"}= notice
.div.m-4
  .page.header
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.doctor.other'))
    .float-end.pb-4
      = link_to t('application.create'), new_doctor_path, class: "btn btn-primary"
    

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.doctor.first_name')
      %th= t('activerecord.attributes.doctor.last_name')
      %th= t('activerecord.attributes.doctor.code')
      %th
      %th
      %th

  %tbody
    - @doctors.each do |doctor|
      %tr
        %td= doctor.first_name
        %td= doctor.last_name
        %td= doctor.code
        %td= link_to t('application.show'), doctor, class: "btn btn-info"
        %td= link_to t('application.edit'), edit_doctor_path(doctor), class: "btn btn-success"
        %td= button_to t('application.delete'), doctor, method: :delete, class: "btn btn-danger"
%br

app/views/doctors/new.html.haml
%h1= t('activerecord.modules.doctor.new')

= render 'form'

app/views/doctors/show.html.haml
%p#notice= notice

%p
  %b First name:
  = @doctor.first_name
%p
  %b Last name:
  = @doctor.last_name
%p
  %b Code:
  = @doctor.code

= link_to 'Edit', edit_doctor_path(@doctor)
\|
= link_to 'Back', doctors_path