config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :patients
  resources :doctors
  resources :contents
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"'
  root "dashboards#index"
end

app/models/appointment.rb
class Appointment < ApplicationRecord
    belongs_to :doctor
    belongs_to :patient
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: %i[ show edit update destroy ]
  before_action :set_doctors
  before_action :set_patients

  def index
    @appointments = Appointment.all
  end

  def show
  end

  def new
    @appointment = Appointment.new
  end

  def edit
  end

  def create
    @appointment = Appointment.new(appointment_params)

    respond_to do |format|
      if @appointment.save
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully created." }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to appointment_url(@appointment), notice: "Appointment was successfully updated." }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @appointment.destroy

    respond_to do |format|
      format.html { redirect_to appointments_url, notice: "Appointment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def set_doctors
      @doctors = Doctor.all.map {| doctor| ["#{doctor.first_name} #{doctor.last_name} - #{doctor.code}", doctor.id]}
    end

    def set_patients
      @patients = Patient.all.map {| patient| ["#{patient.first_name} #{patient.last_name}", patient.id]}
    end

    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    def appointment_params
      params.require(:appointment).permit(:date, :doctor_id, :patient_id)
    end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_appointment.htm.haml
%div{:id => "#{dom_id appointment}"}
  %p
    %strong Doctor:
    = appointment.doctor.first_name
  %p
    %strong Paciente:
    = appointment.patient.first_name
  %p
    %strong Date:
    = appointment.date

app/views/appointments/_appointment.html.haml
%div{:id => "#{dom_id appointment}"}
  %p
    %strong Date:
    = appointment.date
  %p
    %strong Doctor_id:
    = appointment.doctor_id
  %p
    %strong Patient_id:
    = appointment.patient_id

app/views/appointments/_form.html.haml
= form_for @appointment, validate: true do |f|
  -if @appointment.errors.any?
    .card.mx-4
      .card-body
        %div{style: 'color: red'}
          %h2
            = t('application.can_not_be_saved')
          %ul
            -  @appointment.errors.each do |error|
              %li= error.full_message

  .form-group.mx-4
    = f.label :date, class: "form-label required"
    .dev.w-25
      = f.datetime_field :date, autofocus: true, class: "form-control"

  .form-group.mx-4
    = f.label :doctor, class: "form-label required"
    .dev.w-25
      = f.select(:doctor_id, options_for_select(@doctors, @appointment.doctor), {prompt: t('application.select')}, class: "form-control")

  .form-group.mx-4
    = f.label :patient, class: "form-label required"
    .dev.w-25
      = f.select(:patient_id, options_for_select(@patients, @appointment.patient), {prompt: t('application.select')}, class: "form-control")

  .row.mt-4
    .offset-3.col-3
      = link_to t('application.back'), appointments_path, class: "btn btn-secondary btn-block"
    .col-3
      = button_tag t('application.save'), class: "btn btn-outline-success btn-block"

app/views/appointments/edit.html.haml
%h1 Editing appointment

= render 'form'

= link_to 'Show', @appointment
\|
= link_to 'Back', appointments_path

app/views/appointments/index.html.haml
%p{:style => "color: green"}= notice
.div.m-4
  .page.header
    %h1.mb-4
      = t('application.list_of', model: t('activerecord.modules.appointment.other'))
    .float-end.pb-4
      = link_to t('application.create'), new_appointment_path, class: "btn btn-primary"

%table.table.table-striped
  %thead
    %tr
      %th= t('activerecord.attributes.appointment.date')
      %th= t('activerecord.attributes.appointment.doctor')
      %th= t('activerecord.attributes.appointment.patient')
      %th
      %th

  %tbody
    - @appointments.each do |appointment|
      %tr
        %td= appointment.date.strftime("%d/%m/%Y %I:%M %P")
        %td= appointment.doctor.first_name
        %td= appointment.patient.first_name
        %td= link_to 'Show', appointment, class: "btn btn-info"
        %td= link_to 'Edit', edit_appointment_path(appointment), class: "btn btn-success"
        %td= button_to t('application.delete'), appointment, method: :delete, class: "btn btn-danger"

%br

app/views/appointments/new.html.haml
%h1= t('activerecord.appoinment.patient.new')

= render 'form'

app/views/appointments/show.html.haml
%p#notice= notice

%p
  %b Date:
  = @appointment.date

= link_to 'Edit', edit_appointment_path(@appointment)
\|
= link_to 'Back', appointments_path